### ISSUE TITLE
SDK Path not detected correctly

### ISSUE THREAD

**Issue by capnmidnight** [StephenHodgson/MixedRealityToolkit-Unity#8]
If the only Windows 10 SDK that is installed is the one that is required, this code erroneously claims that the SDK is not installed. The sentinel value for `currentSdkVersionIndex` should be changed to a different value (such as -1), or made to be `Nullable<>`.

https://github.com/StephenHodgson/MixedRealityToolkit-Unity/blob/609f055c679b9704054c837d63e4c44e140c8fe8/Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs#L309-L329

**Comment by StephenHodgson** [comment]
Pretty sure this is fixed in the master toolkit fork.

Thanks for bringing this up tho.

**Comment by StephenHodgson** [comment]
https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1585

**Comment by capnmidnight** [comment]
Sorry, I was on a coworkers computer helping them with an issue and didn't notice this was a fork.
